name: Triggered

on:
  repository_dispatch:
    types:
      - test
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event.name == 'repository_dispatch'

    steps:
      - uses: actions/checkout@v4

      - name: Step from triggered workflow
        run: |
          echo "Step from triggered workflow"
