name: Triggered

on:
  workflow_run:
    workflows:
      - Test name
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.outputs.flag == 'true'

    steps:
      - uses: actions/checkout@v4

      - name: Step from triggered workflow
        run: |
          echo "Step from triggered workflow"
